### PR TITLE
Add support of ENV['DATABASE_URL']

### PR DESCRIPTION
**Pull request by donbobka**
My try to add support of environment variable `DATABASE_URL`. In my case I set `DATABASE_URL` with gem `figaro`.

The main change is adding servedside rake task `capistrano_db_tasks:config` that returns remote database configuration.

Side-changes: 
- Add .gitignore, add .editorconfig
- Move all capistrano specific files to capistrano directory.

P.S.: Changes are not backward compatible with previous versions.

### CODE REVIEW

**Comment by numbata** [comment]
Thanks for pull-request, but you did a lot of changes. I'm okay with .gitignore, but not with .editorconfig. I think it should be in your ~/.gitignore_global, because it is your personal setting + someone use vim, someone rubymine, some one prefer emacs.
It's okay about adding DATABASE_URL support, but not with restructurese in one PR. Can you split it onto two PR (one for DATABASE_URL support and one with restructure).

**Comment by donbobka** [comment]
About .editorconfig: it's not about personal choice, it's about common code style for a project. For example, look at ruby repo: https://github.com/ruby/ruby/blob/trunk/.editorconfig
There is a lot of plugins(http://editorconfig.org/#download) for a different editors to support .editorconfig file.

About PR spliting: I'll try to do it

**Comment by numbata** [comment]
@donbobka thanks for the explanation. You're right.

**Comment by fabn** [comment]
Very nice PR. `DATABASE_URL` support is a must for production environments. Any chance to see this merged?

@donbobka Can I point my Gemfile to your fork? Is it stable or it will be rebased/changed to get this merged?

**Comment by fabn** [comment]
I tried this PR using your branch and it works with `DATABASE_URL` however I had to add the gem in production group to make it working. Why don't you implement the fetch config in a cap task? In this way this gem can remain in development group with no need to have it on server. Something like

```ruby
  on roles(:app) do
    within release_path do
      execute(:bundle, 'exec rails runner "ActiveRecord::Base.configurations[Rails.env].to_yaml" > tmp/config.yml')
      db_config = capture('cat tmp/config.yml')
      execute 'rm tmp/config.yml'
    end
  end
```

**Comment by numbata** [comment]
- `DATABASE_URL` support added in PR #70 (merged);
 - `.gitignore` and `.editorconfig` added in PR #95;
 - Capistrano specific files moved to capistrano directory may be in future while refactoring.

So, i close this PR now.

**Pull request closed without merging**
